variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    RUST_BACKTRACE: 1

before_script:
    - rustup component add rustfmt

test:cargo-stable:
    image: "rust:1.52"
    script:
        - rustc --version && cargo --version
        - cargo build --all --all-features --no-default-features
        - time cargo test --jobs 1 --all-features --no-default-features
        - cargo bench -- --test
