[package]
name = "cpd"
version = "0.0.1"
authors = ["Mike Schmidt <schmidmt@gmail.com>"]
edition = "2018"


[dependencies]
rand = "0.6"
rv = { git = "https://gitlab.com/baxe/rv.git", rev="0422f8df" }
