[package]
name = "cpd"
version = "0.1.0"
authors = ["Mike Schmidt <schmidmt@gmail.com>"]
edition = "2018"


[dependencies]
rand = "0.6"
rv = { git = "https://gitlab.com/baxe/rv.git", branch="v0.7.0rc"}
