[package]
name = "changepoint"
version = "0.1.0"
authors = ["Mike Schmidt <schmidmt@gmail.com>"]
edition = "2018"
repository = "https://gitlab.com/Redpoll/changepoint"
keywords = ["Change point detection", "Bayesian", "Machine-Learning", "Statistics"]
categories = ["science"]
license = "MIT"
readme = "README.md"
description = "Change Point Detection in Rust"

[badges]
gitlab = { repository = "https://gitlab.com/Redpoll/changepoint/" }
maintenance = { status = "actively-developed" }

[dependencies]
rand = "0.6"
rv = { git = "https://gitlab.com/baxe/rv.git", tag="v0.7.0rc1" }

[dev-dependencies]
assert = "0.7"
criterion = "0.2"

# Benchmarks
[[bench]]
name = "online_bayesian"
harness = false
