[package]
name = "pychangepoint"
description = "A Python module for changepoint"
version = "0.4.0"
repository = "https://github.com/promised-ai/changepoint"
authors = ["Redpoll <info@redpoll.ai>"]
edition = "2021"
license = "MIT"
publish = false

[workspace]
# prevents package from thinking it's in the workspace

[lib]
name = "changepoint"
crate-type = ["cdylib"]

[dependencies]
bincode = { version = "2.0", features = ["serde"] }
changepoint = { path = "../changepoint", features = ["serde1"] }
nalgebra = { version = "0.34" }
numpy = { version = "0.26", features = ["nalgebra"] }
pyo3 = { version = "0.26", features = ["extension-module"] }
rand = { version = "0.9", features = ["small_rng"] }
rv = { version = "0.19", features = [
    "process",
    "arraydist",
], git = "https://github.com/promised-ai/rv.git", branch = "release/v0.19.0" }
serde = "1.0"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
